builtins_data = '''
[variables]
$ALL_EVENTS|K55
$ALL_GROUPS|K55
$CC_NUM|K55
$CONTROL_PAR_ACTIVE_INDEX|K57
$CONTROL_PAR_ALLOW_AUTOMATION|K55
$CONTROL_PAR_AUTOMATION_ID|K55
$CONTROL_PAR_AUTOMATION_NAME|K55
$CONTROL_PAR_BAR_COLOR|K55
$CONTROL_PAR_BASEPATH|K55
$CONTROL_PAR_BG_ALPHA|K57
$CONTROL_PAR_BG_COLOR|K55
$CONTROL_PAR_COLUMN_WIDTH|K55
$CONTROL_PAR_CURSOR_PICTURE|K57
$CONTROL_PAR_DEFAULT_VALUE|K55
$CONTROL_PAR_DISABLE_TEXT_SHIFTING|K60
$CONTROL_PAR_DND_ACCEPT_ARRAY|K62
$CONTROL_PAR_DND_ACCEPT_AUDIO|K62
$CONTROL_PAR_DND_ACCEPT_MIDI|K62
$CONTROL_PAR_DND_BEHAVIOUR|K55
$CONTROL_PAR_ENABLE_DND|K62
$CONTROL_PAR_FILE_TYPE|K55
$CONTROL_PAR_FILEPATH|K55
$CONTROL_PAR_FONT_TYPE|K55
$CONTROL_PAR_FONT_TYPE_OFF_HOVER|K60
$CONTROL_PAR_FONT_TYPE_OFF_PRESSED|K60
$CONTROL_PAR_FONT_TYPE_ON|K60
$CONTROL_PAR_FONT_TYPE_ON_HOVER|K60
$CONTROL_PAR_FONT_TYPE_ON_PRESSED|K60
$CONTROL_PAR_GRID_HEIGHT|K55
$CONTROL_PAR_GRID_WIDTH|K55
$CONTROL_PAR_GRID_X|K55
$CONTROL_PAR_GRID_Y|K55
$CONTROL_PAR_HEIGHT|K55
$CONTROL_PAR_HELP|K55
$CONTROL_PAR_HIDE|K55
$CONTROL_PAR_KEY_ALT|K55
$CONTROL_PAR_KEY_CONTROL|K55
$CONTROL_PAR_KEY_SHIFT|K55
$CONTROL_PAR_LABEL|K55
$CONTROL_PAR_MAX_VALUE|K55
$CONTROL_PAR_MIDI_EXPORT_AREA_IDX|K64
$CONTROL_PAR_MIN_VALUE|K55
$CONTROL_PAR_MOUSE_BEHAVIOUR|K55
$CONTROL_PAR_MOUSE_BEHAVIOUR_X|K57
$CONTROL_PAR_MOUSE_BEHAVIOUR_Y|K57
$CONTROL_PAR_MOUSE_MODE|K57
$CONTROL_PAR_NONE|K55
$CONTROL_PAR_NUM_ITEMS|K55
$CONTROL_PAR_OFF_COLOR|K55
$CONTROL_PAR_ON_COLOR|K55
$CONTROL_PAR_OVERLOAD_COLOR|K55
$CONTROL_PAR_PARALLAX_X|K60
$CONTROL_PAR_PARALLAX_Y|K60
$CONTROL_PAR_PARENT_PANEL|K61
$CONTROL_PAR_PEAK_COLOR|K55
$CONTROL_PAR_PICTURE|K55
$CONTROL_PAR_PICTURE_STATE|K55
$CONTROL_PAR_POS_X|K55
$CONTROL_PAR_POS_Y|K55
$CONTROL_PAR_RANGE_MAX|K66
$CONTROL_PAR_RANGE_MIN|K66
$CONTROL_PAR_RECEIVE_DRAG_EVENTS|K62
$CONTROL_PAR_SELECTED_ITEM_IDX|K55
$CONTROL_PAR_SHOW_ARROWS|K55
$CONTROL_PAR_SLICEMARKERS_COLOR|K57
$CONTROL_PAR_TEXT|K55
$CONTROL_PAR_TEXT_ALIGNMENT|K55
$CONTROL_PAR_TEXTLINE|K55
$CONTROL_PAR_TEXTPOS_Y|K55
$CONTROL_PAR_UNIT|K55
$CONTROL_PAR_VALUE|K55
$CONTROL_PAR_VERTICAL|K55
$CONTROL_PAR_WAVE_ALPHA|K60
$CONTROL_PAR_WAVE_COLOR|K57
$CONTROL_PAR_WAVE_CURSOR_COLOR|K57
$CONTROL_PAR_WAVE_END_ALPHA|K60
$CONTROL_PAR_WAVE_END_COLOR|K60
$CONTROL_PAR_WAVETABLE_ALPHA|K60
$CONTROL_PAR_WAVETABLE_COLOR|K60
$CONTROL_PAR_WAVETABLE_END_ALPHA|K60
$CONTROL_PAR_WAVETABLE_END_COLOR|K60
$CONTROL_PAR_WF_VIS_MODE|K61
$CONTROL_PAR_WIDTH|K55
$CONTROL_PAR_WT_VIS_MODE|K60
$CONTROL_PAR_WT_ZONE|K60
$CONTROL_PAR_Z_LAYER|K57
$CONTROL_PAR_ZERO_LINE_COLOR|K55
$CURRENT_EVENT|K55
$CURRENT_SCRIPT_SLOT|K55
$DISTANCE_BAR_START|K55
$DURATION_BAR|K55
$DURATION_EIGHTH|K55
$DURATION_EIGHTH_TRIPLET|K55
$DURATION_QUARTER|K55
$DURATION_QUARTER_TRIPLET|K55
$DURATION_SIXTEENTH|K55
$DURATION_SIXTEENTH_TRIPLET|K55
$EFFECT_TYPE_ACBOX|K57
$EFFECT_TYPE_AET_FILTER|K55
$EFFECT_TYPE_BASSINVADER|K67
$EFFECT_TYPE_BASSPRO|K67
$EFFECT_TYPE_BUS_COMP|K55
$EFFECT_TYPE_CABINET|K55
$EFFECT_TYPE_CAT|K57
$EFFECT_TYPE_CHORAL|K62
$EFFECT_TYPE_CHORUS|K55
$EFFECT_TYPE_COMPRESSOR|K55
$EFFECT_TYPE_CRYWAH|K60
$EFFECT_TYPE_DELAY|K55
$EFFECT_TYPE_DISTORTION|K55
$EFFECT_TYPE_DSTORTION|K57
$EFFECT_TYPE_FB_COMP|K55
$EFFECT_TYPE_FILTER|K55
$EFFECT_TYPE_FLAIR|K62
$EFFECT_TYPE_FLANGER|K55
$EFFECT_TYPE_GAINER|K55
$EFFECT_TYPE_HOTSOLO|K57
$EFFECT_TYPE_INVERTER|K55
$EFFECT_TYPE_IRC|K55
$EFFECT_TYPE_JUMP|K55
$EFFECT_TYPE_LIMITER|K55
$EFFECT_TYPE_LOFI|K55
$EFFECT_TYPE_NONE|K55
$EFFECT_TYPE_PHASER|K55
$EFFECT_TYPE_PHASIS|K62
$EFFECT_TYPE_PLATEREVERB|K60
$EFFECT_TYPE_PSYCHEDELAY|K70
$EFFECT_TYPE_REPLIKA|K60
$EFFECT_TYPE_REVERB|K55
$EFFECT_TYPE_REVERB2|K60
$EFFECT_TYPE_RINGMOD|K70
$EFFECT_TYPE_ROTATOR|K55
$EFFECT_TYPE_SEND_LEVELS|K55
$EFFECT_TYPE_SHAPER|K55
$EFFECT_TYPE_SKREAMER|K55
$EFFECT_TYPE_SOLID_GEQ|K55
$EFFECT_TYPE_STEREO|K55
$EFFECT_TYPE_SUPERGT|K63
$EFFECT_TYPE_SURROUND_PANNER|K55
$EFFECT_TYPE_TAPE_SAT|K55
$EFFECT_TYPE_TRANS_MASTER|K55
$EFFECT_TYPE_TRANSLIM|K63
$EFFECT_TYPE_TWANG|K55
$EFFECT_TYPE_VAN51|K57
$ENGINE_PAR_AC_BASS|K57
$ENGINE_PAR_AC_BRILLIANTVOLUME|K57
$ENGINE_PAR_AC_MONO|K57
$ENGINE_PAR_AC_NORMALVOLUME|K57
$ENGINE_PAR_AC_TONECUT|K57
$ENGINE_PAR_AC_TREBLE|K57
$ENGINE_PAR_AC_TREMOLODEPTH|K57
$ENGINE_PAR_AC_TREMOLOSPEED|K57
$ENGINE_PAR_ATK_CURVE|K55
$ENGINE_PAR_ATTACK|K55
$ENGINE_PAR_ATTACK_UNIT|K55
$ENGINE_PAR_AUX_LEVEL_0|K67
$ENGINE_PAR_AUX_LEVEL_1|K67
$ENGINE_PAR_AUX_LEVEL_2|K67
$ENGINE_PAR_AUX_LEVEL_3|K67
$ENGINE_PAR_BANDWIDTH|K55
$ENGINE_PAR_BASSINVADER_BASS|K67
$ENGINE_PAR_BASSINVADER_BOOST|K67
$ENGINE_PAR_BASSINVADER_HI_BOOST|K67
$ENGINE_PAR_BASSINVADER_HI_MID|K67
$ENGINE_PAR_BASSINVADER_LO_CUT|K67
$ENGINE_PAR_BASSINVADER_LO_MID|K67
$ENGINE_PAR_BASSINVADER_MASTER|K67
$ENGINE_PAR_BASSINVADER_MID_CONTOUR|K67
$ENGINE_PAR_BASSINVADER_TREBLE|K67
$ENGINE_PAR_BASSINVADER_VOLUME|K67
$ENGINE_PAR_BASSPRO_BASS|K67
$ENGINE_PAR_BASSPRO_BRIGHT|K67
$ENGINE_PAR_BASSPRO_DRIVE|K67
$ENGINE_PAR_BASSPRO_GAIN|K67
$ENGINE_PAR_BASSPRO_GEQ|K67
$ENGINE_PAR_BASSPRO_GEQ_10K|K67
$ENGINE_PAR_BASSPRO_GEQ_180|K67
$ENGINE_PAR_BASSPRO_GEQ_1K|K67
$ENGINE_PAR_BASSPRO_GEQ_2K|K67
$ENGINE_PAR_BASSPRO_GEQ_300|K67
$ENGINE_PAR_BASSPRO_GEQ_40|K67
$ENGINE_PAR_BASSPRO_GEQ_4K|K67
$ENGINE_PAR_BASSPRO_GEQ_500|K67
$ENGINE_PAR_BASSPRO_GEQ_90|K67
$ENGINE_PAR_BASSPRO_GEQ_VOLUME|K67
$ENGINE_PAR_BASSPRO_MASTER|K67
$ENGINE_PAR_BASSPRO_MID|K67
$ENGINE_PAR_BASSPRO_MIDFREQ|K67
$ENGINE_PAR_BASSPRO_MONO|K67
$ENGINE_PAR_BASSPRO_TREBLE|K67
$ENGINE_PAR_BASSPRO_ULTRAHI|K67
$ENGINE_PAR_BASSPRO_ULTRALO|K67
$ENGINE_PAR_BITS|K55
$ENGINE_PAR_BREAK|K55
$ENGINE_PAR_BW1|K55
$ENGINE_PAR_BW2|K55
$ENGINE_PAR_BW3|K55
$ENGINE_PAR_CABINET_TYPE|K55
$ENGINE_PAR_CB_AIR|K55
$ENGINE_PAR_CB_BASS|K55
$ENGINE_PAR_CB_SIZE|K55
$ENGINE_PAR_CB_TREBLE|K55
$ENGINE_PAR_CH_DEPTH|K55
$ENGINE_PAR_CH_PHASE|K55
$ENGINE_PAR_CH_SPEED|K55
$ENGINE_PAR_CH_SPEED_UNIT|K55
$ENGINE_PAR_CHORAL_AMOUNT|K62
$ENGINE_PAR_CHORAL_DELAY|K62
$ENGINE_PAR_CHORAL_FEEDBACK|K62
$ENGINE_PAR_CHORAL_INVERT_PHASE|K62
$ENGINE_PAR_CHORAL_MIX|K62
$ENGINE_PAR_CHORAL_MODE|K62
$ENGINE_PAR_CHORAL_RATE|K62
$ENGINE_PAR_CHORAL_SCATTER|K62
$ENGINE_PAR_CHORAL_VOICES|K62
$ENGINE_PAR_CHORAL_WIDTH|K62
$ENGINE_PAR_COMP_ATTACK|K55
$ENGINE_PAR_COMP_DECAY|K55
$ENGINE_PAR_COMP_LINK|K64
$ENGINE_PAR_COMP_TYPE|K64
$ENGINE_PAR_CT_BALLS|K57
$ENGINE_PAR_CT_BASS|K57
$ENGINE_PAR_CT_DISTORTION|K57
$ENGINE_PAR_CT_FILTER|K57
$ENGINE_PAR_CT_MONO|K57
$ENGINE_PAR_CT_TONE|K57
$ENGINE_PAR_CT_TREBLE|K57
$ENGINE_PAR_CT_VOLUME|K57
$ENGINE_PAR_CUTOFF|K55
$ENGINE_PAR_CW_MONO|K60
$ENGINE_PAR_CW_PEDAL|K60
$ENGINE_PAR_DAMPING|K55
$ENGINE_PAR_DECAY|K55
$ENGINE_PAR_DECAY1|K55
$ENGINE_PAR_DECAY1_UNIT|K55
$ENGINE_PAR_DECAY2|K55
$ENGINE_PAR_DECAY2_UNIT|K55
$ENGINE_PAR_DECAY_UNIT|K55
$ENGINE_PAR_DISTORTION_TYPE|K57
$ENGINE_PAR_DL_DAMPING|K55
$ENGINE_PAR_DL_FEEDBACK|K55
$ENGINE_PAR_DL_PAN|K55
$ENGINE_PAR_DL_TIME|K55
$ENGINE_PAR_DL_TIME_UNIT|K55
$ENGINE_PAR_DRIVE|K55
$ENGINE_PAR_DS_BASS|K57
$ENGINE_PAR_DS_DRIVE|K57
$ENGINE_PAR_DS_MID|K57
$ENGINE_PAR_DS_MONO|K57
$ENGINE_PAR_DS_TONE|K57
$ENGINE_PAR_DS_TREBLE|K57
$ENGINE_PAR_DS_VOLUME|K57
$ENGINE_PAR_EFFECT_BYPASS|K55
$ENGINE_PAR_EFFECT_SUBTYPE|K55
$ENGINE_PAR_EFFECT_TYPE|K55
$ENGINE_PAR_ENV_AHD|K65
$ENGINE_PAR_ENV_DBD_EASY|K65
$ENGINE_PAR_ENVELOPE_ORDER|K55
$ENGINE_PAR_ENVF_ADAPTION|K63
$ENGINE_PAR_ENVF_ATTACK|K63
$ENGINE_PAR_ENVF_GAIN_BOOST|K63
$ENGINE_PAR_ENVF_RELEASE|K63
$ENGINE_PAR_EXP_FILTER_AMOUNT|K55
$ENGINE_PAR_EXP_FILTER_MORPH|K55
$ENGINE_PAR_EXTMOD_INTENSITY|K55
$ENGINE_PAR_FCOMP_ATTACK|K55
$ENGINE_PAR_FCOMP_HQ_MODE|K57
$ENGINE_PAR_FCOMP_INPUT|K55
$ENGINE_PAR_FCOMP_LINK|K57
$ENGINE_PAR_FCOMP_MAKEUP|K55
$ENGINE_PAR_FCOMP_MIX|K55
$ENGINE_PAR_FCOMP_RATIO|K55
$ENGINE_PAR_FCOMP_RELEASE|K55
$ENGINE_PAR_FILTER_BYPA|K55
$ENGINE_PAR_FILTER_BYPB|K55
$ENGINE_PAR_FILTER_BYPC|K55
$ENGINE_PAR_FILTER_GAIN|K55
$ENGINE_PAR_FILTER_LADDER_HQ|K57
$ENGINE_PAR_FILTER_RESB|K55
$ENGINE_PAR_FILTER_RESC|K55
$ENGINE_PAR_FILTER_SHIFTB|K55
$ENGINE_PAR_FILTER_SHIFTC|K55
$ENGINE_PAR_FILTER_TYPEA|K55
$ENGINE_PAR_FILTER_TYPEB|K55
$ENGINE_PAR_FILTER_TYPEC|K55
$ENGINE_PAR_FL_COLOR|K55
$ENGINE_PAR_FL_DEPTH|K55
$ENGINE_PAR_FL_FEEDBACK|K55
$ENGINE_PAR_FL_PHASE|K55
$ENGINE_PAR_FL_SPEED|K55
$ENGINE_PAR_FL_SPEED_UNIT|K55
$ENGINE_PAR_FLAIR_AMOUNT|K62
$ENGINE_PAR_FLAIR_CHORD|K62
$ENGINE_PAR_FLAIR_DAMPING|K62
$ENGINE_PAR_FLAIR_DETUNE|K62
$ENGINE_PAR_FLAIR_FEEDBACK|K62
$ENGINE_PAR_FLAIR_INVERT_PHASE|K62
$ENGINE_PAR_FLAIR_MIX|K62
$ENGINE_PAR_FLAIR_MODE|K62
$ENGINE_PAR_FLAIR_OFFSET|K62
$ENGINE_PAR_FLAIR_PITCH|K62
$ENGINE_PAR_FLAIR_RATE|K62
$ENGINE_PAR_FLAIR_RATE_UNIT|K62
$ENGINE_PAR_FLAIR_SCANMODE|K62
$ENGINE_PAR_FLAIR_VOICES|K62
$ENGINE_PAR_FLAIR_WIDTH|K62
$ENGINE_PAR_FLEXENV_LOOP|K71
$ENGINE_PAR_FLEXENV_ONESHOT|K71
$ENGINE_PAR_FORMANT|K55
$ENGINE_PAR_FORMANT_SHARP|K55
$ENGINE_PAR_FORMANT_SHIFT|K55
$ENGINE_PAR_FORMANT_SIZE|K55
$ENGINE_PAR_FORMANT_TALK|K55
$ENGINE_PAR_FREQ1|K55
$ENGINE_PAR_FREQ2|K55
$ENGINE_PAR_FREQ3|K55
$ENGINE_PAR_FREQUENCY|K55
$ENGINE_PAR_GAIN|K55
$ENGINE_PAR_GAIN1|K55
$ENGINE_PAR_GAIN2|K55
$ENGINE_PAR_GAIN3|K55
$ENGINE_PAR_GLIDE_COEF|K55
$ENGINE_PAR_GLIDE_COEF_UNIT|K55
$ENGINE_PAR_GN_GAIN|K55
$ENGINE_PAR_GRAIN_LENGTH|K55
$ENGINE_PAR_GROUP_DYNAMICS|K62
$ENGINE_PAR_HOLD|K55
$ENGINE_PAR_HOLD_UNIT|K55
$ENGINE_PAR_HP_CUTOFF|K55
$ENGINE_PAR_HS_BASS|K57
$ENGINE_PAR_HS_DEPTH|K57
$ENGINE_PAR_HS_MASTER|K57
$ENGINE_PAR_HS_MID|K57
$ENGINE_PAR_HS_MONO|K57
$ENGINE_PAR_HS_OVERDRIVE|K57
$ENGINE_PAR_HS_PRENORMAL|K57
$ENGINE_PAR_HS_PREOVERDRIVE|K57
$ENGINE_PAR_HS_PRESENCE|K57
$ENGINE_PAR_HS_TREBLE|K57
$ENGINE_PAR_INSERT_EFFECT_OUTPUT_GAIN|K55
$ENGINE_PAR_INTMOD_BYPASS|K55
$ENGINE_PAR_INTMOD_FREQUENCY|K55
$ENGINE_PAR_INTMOD_FREQUENCY_UNIT|K55
$ENGINE_PAR_INTMOD_INTENSITY|K55
$ENGINE_PAR_INTMOD_PULSEWIDTH|K55
$ENGINE_PAR_INTMOD_RETRIGGER|K61
$ENGINE_PAR_INTMOD_SUBTYPE|K55
$ENGINE_PAR_INTMOD_TYPE|K55
$ENGINE_PAR_IRC_AUTO_GAIN|K71
$ENGINE_PAR_IRC_ER_LR_BOUNDARY|K65
$ENGINE_PAR_IRC_FREQ_HIGHPASS_ER|K55
$ENGINE_PAR_IRC_FREQ_HIGHPASS_LR|K55
$ENGINE_PAR_IRC_FREQ_LOWPASS_ER|K55
$ENGINE_PAR_IRC_FREQ_LOWPASS_LR|K55
$ENGINE_PAR_IRC_LENGTH_RATIO_ER|K55
$ENGINE_PAR_IRC_LENGTH_RATIO_LR|K55
$ENGINE_PAR_IRC_PREDELAY|K55
$ENGINE_PAR_IRC_REVERSE|K65
$ENGINE_PAR_JMP_BASS|K55
$ENGINE_PAR_JMP_HIGAIN|K55
$ENGINE_PAR_JMP_MASTER|K55
$ENGINE_PAR_JMP_MID|K55
$ENGINE_PAR_JMP_MONO|K55
$ENGINE_PAR_JMP_PREAMP|K55
$ENGINE_PAR_JMP_PRESENCE|K55
$ENGINE_PAR_JMP_TREBLE|K55
$ENGINE_PAR_LFO_DELAY|K55
$ENGINE_PAR_LFO_DELAY_UNIT|K55
$ENGINE_PAR_LFO_NORMALIZE|K65
$ENGINE_PAR_LFO_PHASE|K70
$ENGINE_PAR_LFO_RAND|K55
$ENGINE_PAR_LFO_RECT|K55
$ENGINE_PAR_LFO_SAW|K55
$ENGINE_PAR_LFO_SINE|K55
$ENGINE_PAR_LFO_TRI|K55
$ENGINE_PAR_LIM_IN_GAIN|K55
$ENGINE_PAR_LIM_RELEASE|K55
$ENGINE_PAR_LP_CUTOFF|K55
$ENGINE_PAR_LR_SWAP|K64
$ENGINE_PAR_MOD_TARGET_INTENSITY|K55
$ENGINE_PAR_MOD_TARGET_MP_INTENSITY|K70
$ENGINE_PAR_NOISECOLOR|K55
$ENGINE_PAR_NOISELEVEL|K55
$ENGINE_PAR_OUTPUT_CHANNEL|K55
$ENGINE_PAR_PAN|K55
$ENGINE_PAR_PH_DEPTH|K55
$ENGINE_PAR_PH_FEEDBACK|K55
$ENGINE_PAR_PH_PHASE|K55
$ENGINE_PAR_PH_SPEED|K55
$ENGINE_PAR_PH_SPEED_UNIT|K55
$ENGINE_PAR_PHASE_INVERT|K64
$ENGINE_PAR_PHASIS_AMOUNT|K62
$ENGINE_PAR_PHASIS_CENTER|K62
$ENGINE_PAR_PHASIS_FEEDBACK|K62
$ENGINE_PAR_PHASIS_INVERT_MOD_MIX|K62
$ENGINE_PAR_PHASIS_INVERT_PHASE|K62
$ENGINE_PAR_PHASIS_MIX|K62
$ENGINE_PAR_PHASIS_MOD_MIX|K62
$ENGINE_PAR_PHASIS_NOTCHES|K62
$ENGINE_PAR_PHASIS_RATE|K62
$ENGINE_PAR_PHASIS_RATE_UNIT|K62
$ENGINE_PAR_PHASIS_SPREAD|K62
$ENGINE_PAR_PHASIS_STEREO|K62
$ENGINE_PAR_PHASIS_ULTRA|K62
$ENGINE_PAR_POST_FX_SLOT|K65
$ENGINE_PAR_PR_DECAY|K60
$ENGINE_PAR_PR_HIDAMP|K60
$ENGINE_PAR_PR_LOWSHELF|K60
$ENGINE_PAR_PR_PREDELAY|K60
$ENGINE_PAR_PR_STEREO|K60
$ENGINE_PAR_PSYDL_CROSS_FEEDBACK|K70
$ENGINE_PAR_PSYDL_DETUNE|K70
$ENGINE_PAR_PSYDL_DETUNE_STEREO|K70
$ENGINE_PAR_PSYDL_FEEDBACK|K70
$ENGINE_PAR_PSYDL_LR_OFFSET|K70
$ENGINE_PAR_PSYDL_PITCH|K70
$ENGINE_PAR_PSYDL_REVERSE|K70
$ENGINE_PAR_PSYDL_REVERSE_STEREO|K70
$ENGINE_PAR_PSYDL_TIME|K70
$ENGINE_PAR_PSYDL_TIME_UNIT|K70
$ENGINE_PAR_RATIO|K55
$ENGINE_PAR_RDL_AMOUNT|K60
$ENGINE_PAR_RDL_BBDTYPE|K60
$ENGINE_PAR_RDL_DENSE|K60
$ENGINE_PAR_RDL_DEPTH|K60
$ENGINE_PAR_RDL_FEEDBACK|K60
$ENGINE_PAR_RDL_FLUTTER|K60
$ENGINE_PAR_RDL_HIGHCUT|K60
$ENGINE_PAR_RDL_LOWCUT|K60
$ENGINE_PAR_RDL_MODULATION|K60
$ENGINE_PAR_RDL_NOISE|K60
$ENGINE_PAR_RDL_PINGPONG|K60
$ENGINE_PAR_RDL_QUALITY|K60
$ENGINE_PAR_RDL_RATE|K60
$ENGINE_PAR_RDL_SATURATION|K60
$ENGINE_PAR_RDL_SIZE|K60
$ENGINE_PAR_RDL_STEREO|K60
$ENGINE_PAR_RDL_TAPEAGE|K60
$ENGINE_PAR_RDL_TIME|K60
$ENGINE_PAR_RDL_TIME_UNIT|K60
$ENGINE_PAR_RDL_TYPE|K60
$ENGINE_PAR_RELEASE|K55
$ENGINE_PAR_RELEASE_TRIGGER|K55
$ENGINE_PAR_RELEASE_UNIT|K55
$ENGINE_PAR_RESONANCE|K55
$ENGINE_PAR_RINGMOD_EDGE|K70
$ENGINE_PAR_RINGMOD_FAST_MODE|K70
$ENGINE_PAR_RINGMOD_FM|K70
$ENGINE_PAR_RINGMOD_FREQUENCY|K70
$ENGINE_PAR_RINGMOD_LFO_AMOUNT|K70
$ENGINE_PAR_RINGMOD_LFO_RATE|K70
$ENGINE_PAR_RINGMOD_LFO_WAVE|K70
$ENGINE_PAR_RINGMOD_RING|K70
$ENGINE_PAR_RT_ACCEL_HI|K55
$ENGINE_PAR_RT_ACCEL_LO|K55
$ENGINE_PAR_RT_BALANCE|K55
$ENGINE_PAR_RT_DISTANCE|K55
$ENGINE_PAR_RT_MIX|K55
$ENGINE_PAR_RT_SPEED|K55
$ENGINE_PAR_RV2_DAMPING|K60
$ENGINE_PAR_RV2_DIFF|K60
$ENGINE_PAR_RV2_HIGHCUT|K60
$ENGINE_PAR_RV2_LOWSHELF|K60
$ENGINE_PAR_RV2_MOD|K60
$ENGINE_PAR_RV2_PREDELAY|K60
$ENGINE_PAR_RV2_SIZE|K60
$ENGINE_PAR_RV2_STEREO|K60
$ENGINE_PAR_RV2_TIME|K60
$ENGINE_PAR_RV2_TYPE|K60
$ENGINE_PAR_RV_COLOUR|K55
$ENGINE_PAR_RV_DAMPING|K55
$ENGINE_PAR_RV_PREDELAY|K55
$ENGINE_PAR_RV_SIZE|K55
$ENGINE_PAR_RV_STEREO|K55
$ENGINE_PAR_SCOMP_ATTACK|K55
$ENGINE_PAR_SCOMP_LINK|K64
$ENGINE_PAR_SCOMP_MAKEUP|K55
$ENGINE_PAR_SCOMP_MIX|K55
$ENGINE_PAR_SCOMP_RATIO|K55
$ENGINE_PAR_SCOMP_RELEASE|K55
$ENGINE_PAR_SCOMP_THRESHOLD|K55
$ENGINE_PAR_SEND_EFFECT_BYPASS|K55
$ENGINE_PAR_SEND_EFFECT_DRY_LEVEL|K55
$ENGINE_PAR_SEND_EFFECT_OUTPUT_GAIN|K55
$ENGINE_PAR_SEND_EFFECT_TYPE|K55
$ENGINE_PAR_SENDLEVEL_0|K55
$ENGINE_PAR_SENDLEVEL_1|K55
$ENGINE_PAR_SENDLEVEL_2|K55
$ENGINE_PAR_SENDLEVEL_3|K55
$ENGINE_PAR_SENDLEVEL_4|K55
$ENGINE_PAR_SENDLEVEL_5|K55
$ENGINE_PAR_SENDLEVEL_6|K55
$ENGINE_PAR_SENDLEVEL_7|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_0|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_1|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_2|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_3|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_4|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_5|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_6|K55
$ENGINE_PAR_SENDLEVEL_SMOOTHED_7|K55
$ENGINE_PAR_SEQ_HF_BELL|K55
$ENGINE_PAR_SEQ_HF_FREQ|K55
$ENGINE_PAR_SEQ_HF_GAIN|K55
$ENGINE_PAR_SEQ_HMF_FREQ|K55
$ENGINE_PAR_SEQ_HMF_GAIN|K55
$ENGINE_PAR_SEQ_HMF_Q|K55
$ENGINE_PAR_SEQ_LF_BELL|K55
$ENGINE_PAR_SEQ_LF_FREQ|K55
$ENGINE_PAR_SEQ_LF_GAIN|K55
$ENGINE_PAR_SEQ_LMF_FREQ|K55
$ENGINE_PAR_SEQ_LMF_GAIN|K55
$ENGINE_PAR_SEQ_LMF_Q|K55
$ENGINE_PAR_SHAPE|K55
$ENGINE_PAR_SHAPE_TYPE|K57
$ENGINE_PAR_SK_BASS|K55
$ENGINE_PAR_SK_BRIGHT|K55
$ENGINE_PAR_SK_DRIVE|K55
$ENGINE_PAR_SK_MIX|K55
$ENGINE_PAR_SK_TONE|K55
$ENGINE_PAR_SLICE_ATTACK|K55
$ENGINE_PAR_SLICE_RELEASE|K55
$ENGINE_PAR_SMOOTH|K55
$ENGINE_PAR_SP_DIVERGENCE|K55
$ENGINE_PAR_SP_LFE_VOLUME|K55
$ENGINE_PAR_SP_OFFSET_AZIMUTH|K55
$ENGINE_PAR_SP_OFFSET_DISTANCE|K55
$ENGINE_PAR_SP_OFFSET_X|K55
$ENGINE_PAR_SP_OFFSET_Y|K55
$ENGINE_PAR_SP_SIZE|K55
$ENGINE_PAR_SPEED|K55
$ENGINE_PAR_SPEED_UNIT|K55
$ENGINE_PAR_START_CRITERIA_CC_MAX|K55
$ENGINE_PAR_START_CRITERIA_CC_MIN|K55
$ENGINE_PAR_START_CRITERIA_CONTROLLER|K55
$ENGINE_PAR_START_CRITERIA_CYCLE_CLASS|K55
$ENGINE_PAR_START_CRITERIA_KEY_MAX|K55
$ENGINE_PAR_START_CRITERIA_KEY_MIN|K55
$ENGINE_PAR_START_CRITERIA_MODE|K55
$ENGINE_PAR_START_CRITERIA_NEXT_CRIT|K55
$ENGINE_PAR_START_CRITERIA_SEQ_ONLY|K55
$ENGINE_PAR_START_CRITERIA_SLICE_IDX|K55
$ENGINE_PAR_START_CRITERIA_ZONE_IDX|K55
$ENGINE_PAR_STEPSEQ_NUM_STEPS|K70
$ENGINE_PAR_STEPSEQ_ONESHOT|K70
$ENGINE_PAR_STEPSEQ_STEP_VALUE|K70
$ENGINE_PAR_STEREO|K55
$ENGINE_PAR_STEREO_PAN|K55
$ENGINE_PAR_STEREO_PSEUDO|K64
$ENGINE_PAR_SUPERGT_ATTACK|K63
$ENGINE_PAR_SUPERGT_CHANNEL_LINK_MODE|K63
$ENGINE_PAR_SUPERGT_CHAR_MODE|K63
$ENGINE_PAR_SUPERGT_CHARACTER|K63
$ENGINE_PAR_SUPERGT_COMPRESS|K63
$ENGINE_PAR_SUPERGT_HPF_MODE|K63
$ENGINE_PAR_SUPERGT_MIX|K63
$ENGINE_PAR_SUPERGT_RELEASE|K63
$ENGINE_PAR_SUPERGT_SAT_MODE|K63
$ENGINE_PAR_SUPERGT_SATURATION|K63
$ENGINE_PAR_SUPERGT_TRIM|K63
$ENGINE_PAR_SUSTAIN|K55
$ENGINE_PAR_THRESHOLD|K55
$ENGINE_PAR_TP_GAIN|K55
$ENGINE_PAR_TP_HF_ROLLOFF|K55
$ENGINE_PAR_TP_QUALITY|K57
$ENGINE_PAR_TP_WARMTH|K55
$ENGINE_PAR_TR_ATTACK|K55
$ENGINE_PAR_TR_INPUT|K55
$ENGINE_PAR_TR_SMOOTH|K57
$ENGINE_PAR_TR_SUSTAIN|K55
$ENGINE_PAR_TRANSIENT_SIZE|K55
$ENGINE_PAR_TRANSLIM_CEILING|K63
$ENGINE_PAR_TRANSLIM_RELEASE|K63
$ENGINE_PAR_TRANSLIM_THRESHOLD|K63
$ENGINE_PAR_TM_LEGATO|K71
$ENGINE_PAR_TUNE|K55
$ENGINE_PAR_TW_BASS|K55
$ENGINE_PAR_TW_BRIGHT|K57
$ENGINE_PAR_TW_MID|K55
$ENGINE_PAR_TW_MONO|K57
$ENGINE_PAR_TW_TREBLE|K55
$ENGINE_PAR_TW_VOLUME|K55
$ENGINE_PAR_V5_BASS|K57
$ENGINE_PAR_V5_BRIGHT|K57
$ENGINE_PAR_V5_CRUNCH|K57
$ENGINE_PAR_V5_HIGAIN|K57
$ENGINE_PAR_V5_LEADCHANNEL|K57
$ENGINE_PAR_V5_MID|K57
$ENGINE_PAR_V5_MONO|K57
$ENGINE_PAR_V5_POSTGAIN|K57
$ENGINE_PAR_V5_PREGAINLEAD|K57
$ENGINE_PAR_V5_PREGAINRHYTHM|K57
$ENGINE_PAR_V5_PRESENCE|K57
$ENGINE_PAR_V5_RESONANCE|K57
$ENGINE_PAR_V5_TREBLE|K57
$ENGINE_PAR_VOLUME|K55
$ENGINE_PAR_WT_FORM|K60
$ENGINE_PAR_WT_FORM_MODE|K60
$ENGINE_PAR_WT_INHARMONIC|K61
$ENGINE_PAR_WT_INHARMONIC_MODE|K61
$ENGINE_PAR_WT_PHASE|K60
$ENGINE_PAR_WT_PHASE_RAND|K60
$ENGINE_PAR_WT_POSITION|K60
$ENGINE_PAR_WT_QUALITY|K60
$ENGINE_UPTIME|K55
$ENV_TYPE_AHDSR|K55
$ENV_TYPE_DBD|K55
$ENV_TYPE_FLEX|K55
$EVENT_ID|K55
$EVENT_NOTE|K55
$EVENT_PAR_0|K55
$EVENT_PAR_1|K55
$EVENT_PAR_2|K55
$EVENT_PAR_3|K55
$EVENT_PAR_ALLOW_GROUP|K55
$EVENT_PAR_CUSTOM|K64
$EVENT_PAR_ID|K55
$EVENT_PAR_MIDI_BYTE_1|K55
$EVENT_PAR_MIDI_BYTE_2|K55
$EVENT_PAR_MIDI_CHANNEL|K55
$EVENT_PAR_MIDI_COMMAND|K55
$EVENT_PAR_MOD_VALUE_ID|K66
$EVENT_PAR_MOD_VALUE_EX_ID|K71
$EVENT_PAR_NOTE|K55
$EVENT_PAR_NOTE_LENGTH|K55
$EVENT_PAR_PAN|K55
$EVENT_PAR_PLAY_POS|K55
$EVENT_PAR_POS|K55
$EVENT_PAR_REL_VELOCITY|K63
$EVENT_PAR_SOURCE|K55
$EVENT_PAR_TRACK_NR|K55
$EVENT_PAR_TUNE|K55
$EVENT_PAR_VELOCITY|K55
$EVENT_PAR_VOLUME|K55
$EVENT_PAR_ZONE_ID|K55
$EVENT_STATUS_INACTIVE|K55
$EVENT_STATUS_MIDI_QUEUE|K55
$EVENT_STATUS_NOTE_QUEUE|K55
$EVENT_VELOCITY|K55
$FILTER_TYPE_AR_BP2|K55
$FILTER_TYPE_AR_BP24|K55
$FILTER_TYPE_AR_BP4|K55
$FILTER_TYPE_AR_HP2|K55
$FILTER_TYPE_AR_HP24|K55
$FILTER_TYPE_AR_HP4|K55
$FILTER_TYPE_AR_LP2|K55
$FILTER_TYPE_AR_LP24|K55
$FILTER_TYPE_AR_LP4|K55
$FILTER_TYPE_BP2POLE|K55
$FILTER_TYPE_BP4POLE|K55
$FILTER_TYPE_BR4POLE|K55
$FILTER_TYPE_DAFT_HP|K55
$FILTER_TYPE_DAFT_LP|K55
$FILTER_TYPE_EQ1BAND|K55
$FILTER_TYPE_EQ2BAND|K55
$FILTER_TYPE_EQ3BAND|K55
$FILTER_TYPE_FORMANT_1|K55
$FILTER_TYPE_FORMANT_2|K55
$FILTER_TYPE_HP1POLE|K55
$FILTER_TYPE_HP2POLE|K55
$FILTER_TYPE_HP4POLE|K55
$FILTER_TYPE_LADDER|K55
$FILTER_TYPE_LDR_BP2|K55
$FILTER_TYPE_LDR_BP4|K55
$FILTER_TYPE_LDR_HP1|K55
$FILTER_TYPE_LDR_HP2|K55
$FILTER_TYPE_LDR_HP3|K55
$FILTER_TYPE_LDR_HP4|K55
$FILTER_TYPE_LDR_LP1|K55
$FILTER_TYPE_LDR_LP2|K55
$FILTER_TYPE_LDR_LP3|K55
$FILTER_TYPE_LDR_LP4|K55
$FILTER_TYPE_LDR_NOTCH|K55
$FILTER_TYPE_LDR_PEAK|K55
$FILTER_TYPE_LP1POLE|K55
$FILTER_TYPE_LP2POLE|K55
$FILTER_TYPE_LP4POLE|K55
$FILTER_TYPE_LP6POLE|K55
$FILTER_TYPE_PHASER|K55
$FILTER_TYPE_PRO52|K55
$FILTER_TYPE_SIMPLE_LPHP|K55
$FILTER_TYPE_SV_BP2|K55
$FILTER_TYPE_SV_BP4|K55
$FILTER_TYPE_SV_BP6|K71
$FILTER_TYPE_SV_HP1|K55
$FILTER_TYPE_SV_HP2|K55
$FILTER_TYPE_SV_HP4|K55
$FILTER_TYPE_SV_HP6|K71
$FILTER_TYPE_SV_LP1|K55
$FILTER_TYPE_SV_LP2|K55
$FILTER_TYPE_SV_LP4|K55
$FILTER_TYPE_SV_LP6|K71
$FILTER_TYPE_SV_NOTCH4|K55
$FILTER_TYPE_SV_NOTCH6|K71
$FILTER_TYPE_SV_PAR_BPBP|K55
$FILTER_TYPE_SV_PAR_LPHP|K55
$FILTER_TYPE_SV_SER_LPHP|K55
$FILTER_TYPE_VERSATILE|K55
$FILTER_TYPE_VOWELA|K55
$FILTER_TYPE_VOWELB|K55
$GET_FOLDER_FACTORY_DIR|K55
$GET_FOLDER_INSTALL_DIR|K55
$GET_FOLDER_LIBRARY_DIR|K55
$GET_FOLDER_PATCH_DIR|K55
$HIDE_PART_BG|K55
$HIDE_PART_CURSOR|K57
$HIDE_PART_MOD_LIGHT|K55
$HIDE_PART_NOTHING|K55
$HIDE_PART_TITLE|K55
$HIDE_PART_VALUE|K55
$HIDE_WHOLE_CONTROL|K55
$IDX_OFFSET_EXT_MOD|K55
$INST_ICON_ID|K55
$INST_LIB_COPYRIGHT_ID|K55
$INST_LIB_DESCRIPTION_ID|K55
$INST_LIB_PIC_ONE_ID|K55
$INST_LIB_PIC_TWO_ID|K55
$INST_PERFVIEW_ID|K60
$INST_WALLPAPER_ID|K55
$INTMOD_TYPE_ENV_FOLLOW|K55
$INTMOD_TYPE_ENVELOPE|K55
$INTMOD_TYPE_GLIDE|K55
$INTMOD_TYPE_LFO|K55
$INTMOD_TYPE_NONE|K55
$INTMOD_TYPE_STEPMOD|K55
$KEY_COLOR_BLACK|K55
$KEY_COLOR_BLUE|K55
$KEY_COLOR_CYAN|K55
$KEY_COLOR_DEFAULT|K55
$KEY_COLOR_FUCHSIA|K55
$KEY_COLOR_GREEN|K55
$KEY_COLOR_INACTIVE|K55
$KEY_COLOR_LIGHT_ORANGE|K55
$KEY_COLOR_LIME|K55
$KEY_COLOR_MAGENTA|K55
$KEY_COLOR_MINT|K55
$KEY_COLOR_NONE|K55
$KEY_COLOR_ORANGE|K55
$KEY_COLOR_PLUM|K55
$KEY_COLOR_PURPLE|K55
$KEY_COLOR_RED|K55
$KEY_COLOR_TURQUOISE|K55
$KEY_COLOR_VIOLET|K55
$KEY_COLOR_WARM_YELLOW|K55
$KEY_COLOR_WHITE|K55
$KEY_COLOR_YELLOW|K55
$KNOB_UNIT_DB|K55
$KNOB_UNIT_HZ|K55
$KNOB_UNIT_MS|K55
$KNOB_UNIT_NONE|K55
$KNOB_UNIT_OCT|K55
$KNOB_UNIT_PERCENT|K55
$KNOB_UNIT_ST|K55
$KSP_TIMER|K55
$LFO_TYPE_MULTI|K55
$LFO_TYPE_MULTI_DIGITAL|K60
$LFO_TYPE_RANDOM|K55
$LFO_TYPE_RECTANGLE|K55
$LFO_TYPE_SAWTOOTH|K55
$LFO_TYPE_SINE|K55
$LFO_TYPE_TRIANGLE|K55
$LOOP_PAR_COUNT|K62
$LOOP_PAR_LENGTH|K62
$LOOP_PAR_MODE|K62
$LOOP_PAR_START|K62
$LOOP_PAR_TUNING|K62
$LOOP_PAR_XFADE|K62
$MARK_1|K55
$MARK_2|K55
$MARK_3|K55
$MARK_4|K55
$MARK_5|K55
$MARK_6|K55
$MARK_7|K55
$MARK_8|K55
$MARK_9|K55
$MARK_10|K55
$MARK_11|K55
$MARK_12|K55
$MARK_13|K55
$MARK_14|K55
$MARK_15|K55
$MARK_16|K55
$MARK_17|K55
$MARK_18|K55
$MARK_19|K55
$MARK_20|K55
$MARK_21|K55
$MARK_22|K55
$MARK_23|K55
$MARK_24|K55
$MARK_25|K55
$MARK_26|K55
$MARK_27|K55
$MARK_28|K55
$MIDI_BYTE_1|K55
$MIDI_BYTE_2|K55
$MIDI_CHANNEL|K55
$MIDI_COMMAND|K55
$MIDI_COMMAND_CC|K55
$MIDI_COMMAND_MONO_AT|K55
$MIDI_COMMAND_NOTE_OFF|K55
$MIDI_COMMAND_NOTE_ON|K55
$MIDI_COMMAND_NRPN|K55
$MIDI_COMMAND_PITCH_BEND|K55
$MIDI_COMMAND_POLY_AT|K55
$MIDI_COMMAND_PROGRAM_CHANGE|K55
$MIDI_COMMAND_RPN|K55
$MOD_TARGET_INVERT_SOURCE|K55
$NI_ASYNC_EXIT_STATUS|K55
$NI_ASYNC_ID|K55
$NI_BAR_START_POSITION|K60
$NI_BUS_OFFSET|K55
$NI_CALLBACK_ID|K55
$NI_CALLBACK_TYPE|K55
$NI_CB_TYPE_ASYNC_COMPLETE|K55
$NI_CB_TYPE_CONTROLLER|K55
$NI_CB_TYPE_INIT|K55
$NI_CB_TYPE_LISTENER|K55
$NI_CB_TYPE_MIDI_IN|K55
$NI_CB_TYPE_NOTE|K55
$NI_CB_TYPE_NRPN|K55
$NI_CB_TYPE_PERSISTENCE_CHANGED|K55
$NI_CB_TYPE_PGS|K55
$NI_CB_TYPE_POLY_AT|K55
$NI_CB_TYPE_RELEASE|K55
$NI_CB_TYPE_RPN|K55
$NI_CB_TYPE_UI_CONTROL|K55
$NI_CB_TYPE_UI_UPDATE|K55
$NI_CHORAL_MODE_DIMENSION|K62
$NI_CHORAL_MODE_ENSEMBLE|K62
$NI_CHORAL_MODE_SYNTH|K62
$NI_CHORAL_MODE_UNIVERSAL|K62
$NI_COMP_TYPE_CLASSIC|K64
$NI_COMP_TYPE_ENHANCED|K64
$NI_COMP_TYPE_PRO|K64
$NI_CONTROL_PAR_IDX|K57
$NI_DETECT_DRUM_TYPE_CLAP|K62
$NI_DETECT_DRUM_TYPE_CLOSED_HH|K62
$NI_DETECT_DRUM_TYPE_CYMBAL|K62
$NI_DETECT_DRUM_TYPE_INVALID|K62
$NI_DETECT_DRUM_TYPE_KICK|K62
$NI_DETECT_DRUM_TYPE_OPEN_HH|K62
$NI_DETECT_DRUM_TYPE_PERC_DRUM|K62
$NI_DETECT_DRUM_TYPE_PERC_OTHER|K62
$NI_DETECT_DRUM_TYPE_SHAKER|K62
$NI_DETECT_DRUM_TYPE_SNARE|K62
$NI_DETECT_DRUM_TYPE_TOM|K62
$NI_DETECT_INSTRUMENT_TYPE_BASS|K62
$NI_DETECT_INSTRUMENT_TYPE_BOWED_STRING|K62
$NI_DETECT_INSTRUMENT_TYPE_BRASS|K62
$NI_DETECT_INSTRUMENT_TYPE_FLUTE|K62
$NI_DETECT_INSTRUMENT_TYPE_GUITAR|K62
$NI_DETECT_INSTRUMENT_TYPE_INVALID|K62
$NI_DETECT_INSTRUMENT_TYPE_KEYBOARD|K62
$NI_DETECT_INSTRUMENT_TYPE_MALLET|K62
$NI_DETECT_INSTRUMENT_TYPE_ORGAN|K62
$NI_DETECT_INSTRUMENT_TYPE_PLUCKED_STRING|K62
$NI_DETECT_INSTRUMENT_TYPE_REED|K62
$NI_DETECT_INSTRUMENT_TYPE_SYNTH|K62
$NI_DETECT_INSTRUMENT_TYPE_VOCAL|K62
$NI_DETECT_SAMPLE_TYPE_DRUM|K62
$NI_DETECT_SAMPLE_TYPE_INSTRUMENT|K62
$NI_DETECT_SAMPLE_TYPE_INVALID|K62
$NI_DISTORTION_TYPE_TRANS|K57
$NI_DISTORTION_TYPE_TUBE|K57
$NI_DND_ACCEPT_MULTIPLE|K62
$NI_DND_ACCEPT_NONE|K62
$NI_DND_ACCEPT_ONE|K62
$NI_FILE_EXTENSION|K62
$NI_FILE_FULL_PATH|K62
$NI_FILE_FULL_PATH_OS|K62
$NI_FILE_NAME|K62
$NI_FILE_TYPE_ARRAY|K55
$NI_FILE_TYPE_AUDIO|K55
$NI_FILE_TYPE_MIDI|K55
$NI_FLAIR_MODE_SCAN|K62
$NI_FLAIR_MODE_STANDARD|K62
$NI_FLAIR_MODE_THRU_ZERO|K62
$NI_FLAIR_SCANMODE_SAW_DOWN|K62
$NI_FLAIR_SCANMODE_SAW_UP|K62
$NI_FLAIR_SCANMODE_TRIANGLE|K62
$NI_GROUP_PAR_COLOR|K63
$NI_GROUP_PAR_HIGH_KEY|K63
$NI_GROUP_PAR_LOW_KEY|K63
$NI_GROUP_PAR_NUM_ZONES|K63
$NI_INSERT_BUS|K64
$NI_KEY_TYPE_CONTROL|K55
$NI_KEY_TYPE_DEFAULT|K55
$NI_KEY_TYPE_NONE|K55
$NI_KONTAKT_IS_HEADLESS|K65
$NI_LEVEL_METER_GROUP|K66
$NI_LEVEL_METER_INSERT|K66
$NI_LEVEL_METER_MAIN|K66
$NI_LOG_MESSAGE|K60
$NI_LOG_WARNING|K60
$NI_LOG_WATCHING|K60
$NI_MAIN_BUS|K64
$NI_MOUSE_EVENT_TYPE|K60
$NI_MOUSE_EVENT_TYPE_DRAG|K60
$NI_MOUSE_EVENT_TYPE_DROP|K62
$NI_MOUSE_EVENT_TYPE_LEFT_BUTTON_DOWN|K60
$NI_MOUSE_EVENT_TYPE_LEFT_BUTTON_UP|K60
$NI_MOUSE_OVER_CONTROL|K62
$NI_NOT_FOUND|K71
$NI_REPLIKA_TYPE_ANALOGUE|K60
$NI_REPLIKA_TYPE_DIFFUSION|K60
$NI_REPLIKA_TYPE_MODERN|K60
$NI_REPLIKA_TYPE_TAPE|K60
$NI_REPLIKA_TYPE_VINTAGE|K60
$NI_REVERB2_TYPE_HALL|K60
$NI_REVERB2_TYPE_ROOM|K60
$NI_RINGMOD_LFO_WAVE_SINE|K70
$NI_RINGMOD_LFO_WAVE_SQUARE|K70
$NI_SEND_BUS|K64
$NI_SHAPE_TYPE_CLASSIC|K57
$NI_SHAPE_TYPE_DRUMS|K57
$NI_SHAPE_TYPE_ENHANCED|K57
$NI_SIGNAL_TIMER_BEAT|K55
$NI_SIGNAL_TIMER_MS|K55
$NI_SIGNAL_TRANSP_START|K55
$NI_SIGNAL_TRANSP_STOP|K55
$NI_SIGNAL_TYPE|K55
$NI_SONG_POSITION|K55
$NI_SUPERGT_CHANNEL_LINK_MODE_DUAL_MONO|K63
$NI_SUPERGT_CHANNEL_LINK_MODE_MS|K63
$NI_SUPERGT_CHANNEL_LINK_MODE_STEREO|K63
$NI_SUPERGT_CHAR_MODE_BRIGHT|K63
$NI_SUPERGT_CHAR_MODE_FAT|K63
$NI_SUPERGT_CHAR_MODE_WARM|K63
$NI_SUPERGT_HPF_MODE_100|K63
$NI_SUPERGT_HPF_MODE_300|K63
$NI_SUPERGT_HPF_MODE_OFF|K63
$NI_SUPERGT_SAT_MODE_HOT|K63
$NI_SUPERGT_SAT_MODE_MILD|K63
$NI_SUPERGT_SAT_MODE_MODERATE|K63
$NI_SYNC_UNIT_16TH|K55
$NI_SYNC_UNIT_16TH_TRIPLET|K55
$NI_SYNC_UNIT_256TH|K55
$NI_SYNC_UNIT_32ND|K55
$NI_SYNC_UNIT_32ND_TRIPLET|K55
$NI_SYNC_UNIT_64TH|K55
$NI_SYNC_UNIT_64TH_TRIPLET|K55
$NI_SYNC_UNIT_8TH|K55
$NI_SYNC_UNIT_8TH_TRIPLET|K55
$NI_SYNC_UNIT_ABS|K55
$NI_SYNC_UNIT_HALF|K55
$NI_SYNC_UNIT_HALF_TRIPLET|K55
$NI_SYNC_UNIT_QUARTER|K55
$NI_SYNC_UNIT_QUARTER_TRIPLET|K55
$NI_SYNC_UNIT_WHOLE|K55
$NI_SYNC_UNIT_WHOLE_TRIPLET|K55
$NI_SYNC_UNIT_ZONE|K55
$NI_TRANSPORT_RUNNING|K55
$NI_VL_TMPRO_HQ|K55
$NI_VL_TMPRO_STANDARD|K55
$NI_WF_VIS_MODE_1|K61
$NI_WF_VIS_MODE_2|K61
$NI_WF_VIS_MODE_3|K61
$NI_WT_FORM_ASYMM|K60
$NI_WT_FORM_ASYMMP|K60
$NI_WT_FORM_ASYMP|K60
$NI_WT_FORM_BENDM|K60
$NI_WT_FORM_BENDMP|K60
$NI_WT_FORM_BENDP|K60
$NI_WT_FORM_FLIP|K60
$NI_WT_FORM_LINEAR|K60
$NI_WT_FORM_MIRROR|K60
$NI_WT_FORM_PWM|K60
$NI_WT_FORM_QUANTIZE|K60
$NI_WT_FORM_SYNC1|K60
$NI_WT_FORM_SYNC2|K60
$NI_WT_FORM_SYNC3|K60
$NI_WT_QUALITY_BEST|K60
$NI_WT_QUALITY_HIGH|K60
$NI_WT_QUALITY_LOFI|K60
$NI_WT_QUALITY_MEDIUM|K60
$NI_WT_VIS_2D|K60
$NI_WT_VIS_3D|K60
$NOTE_HELD|K55
$NUM_GROUPS|K55
$NUM_OUTPUT_CHANNELS|K55
$NUM_ZONES|K55
$OUTPUT_TYPE_AUX_OUT|K66
$OUTPUT_TYPE_BUS_OUT|K66
$OUTPUT_TYPE_DEFAULT|K66
$OUTPUT_TYPE_MASTER_OUT|K66
$PLAYED_VOICES_INST|K55
$PLAYED_VOICES_TOTAL|K55
$POLY_AT_NUM|K55
$REF_GROUP_IDX|K55
$RPN_ADDRESS|K55
$RPN_VALUE|K55
$SIGNATURE_DENOM|K55
$SIGNATURE_NUM|K55
$START_CRITERIA_AND_NEXT|K55
$START_CRITERIA_AND_NOT_NEXT|K55
$START_CRITERIA_CYCLE_RANDOM|K55
$START_CRITERIA_CYCLE_ROUND_ROBIN|K55
$START_CRITERIA_NONE|K55
$START_CRITERIA_ON_CONTROLLER|K55
$START_CRITERIA_ON_KEY|K55
$START_CRITERIA_OR_NEXT|K55
$START_CRITERIA_SLICE_TRIGGER|K55
$UI_WAVEFORM_TABLE_IS_BIPOLAR|K55
$UI_WAVEFORM_USE_MIDI_DRAG|K55
$UI_WAVEFORM_USE_SLICES|K55
$UI_WAVEFORM_USE_TABLE|K55
$UI_WF_PROP_FLAGS|K55
$UI_WF_PROP_MIDI_DRAG_START_NOTE|K55
$UI_WF_PROP_PLAY_CURSOR|K55
$UI_WF_PROP_TABLE_IDX_HIGHLIGHT|K55
$UI_WF_PROP_TABLE_VAL|K55
$VALUE_EDIT_MODE_NOTE_NAMES|K55
$VCC_MONO_AT|K55
$VCC_PITCH_BEND|K55
$ZONE_PAR_BPM|K71
$ZONE_PAR_FADE_HIGH_KEY|K62
$ZONE_PAR_FADE_HIGH_VELO|K62
$ZONE_PAR_FADE_LOW_KEY|K62
$ZONE_PAR_FADE_LOW_VELO|K62
$ZONE_PAR_GROUP|K62
$ZONE_PAR_HIGH_KEY|K62
$ZONE_PAR_HIGH_VELO|K62
$ZONE_PAR_LOW_KEY|K62
$ZONE_PAR_LOW_VELO|K62
$ZONE_PAR_PAN|K62
$ZONE_PAR_ROOT_KEY|K62
$ZONE_PAR_SAMPLE_END|K62
$ZONE_PAR_SAMPLE_MOD_RANGE|K62
$ZONE_PAR_SAMPLE_RATE|K71
$ZONE_PAR_SAMPLE_START|K62
$ZONE_PAR_TUNE|K62
$ZONE_PAR_VOLUME|K62
%CC|K55
%CC_TOUCHED|K55
%EVENT_PAR|K55
%GROUPS_AFFECTED|K55
%GROUPS_SELECTED|K55
%KEY_DOWN|K55
%KEY_DOWN_OCT|K55
%NI_USER_ZONE_IDS|K62
%NOTE_DURATION|K55
%POLY_AT|K55
~NI_DETECT_LOUDNESS_INVALID|K62
~NI_DETECT_PEAK_INVALID|K62
~NI_DETECT_PITCH_INVALID|K62
~NI_DETECT_RMS_INVALID|K62
~NI_MATH_E|K56
~NI_MATH_PI|K56
!NI_DND_ITEMS_ARRAY|K62
!NI_DND_ITEMS_AUDIO|K62
!NI_DND_ITEMS_MIDI|K62

[functions]
END_USE_CODE()|K55
RESET_CONDITION(<condition>)|K55
SET_CONDITION(<condition>)|K55
USE_CODE_IF(<condition>)|K55
USE_CODE_IF_NOT(<condition>)|K55
_delay_event_for_loading_slots(<unknown>)|K55
_get_engine_par(<parameter>, <group>, <slot>, <generic>):integer|K62
_get_engine_par_disp(<parameter>, <group>, <slot>, <generic>):string|K62
_get_folder(<path variable>):string|K55
_load_ir_sample(<file-name>, <slot>, <generic>):integer|K62
_num_slices(<group-idx>):integer|K62
_pgs_create_key(<key-id>, <size>)|K62
_pgs_get_key_val(<key-id>, <index>):integer|K62
_pgs_key_exists(<key-id>):boolean|K55
_pgs_set_key_val(<key-id>, <index>, <value>)|K62
_read_persistent_var(<variable>)|K55
_reset_rls_trig_counter(<note>)|K55
_set_engine_par(<parameter>, <value>, <group>, <slot>, <generic>):integer|K62
_set_skin_offset(<offset>)|K55
_slice_idx_loop_end(<group-idx>, <loop-idx>):integer|K62
_slice_idx_loop_start(<group-idx>, <loop-idx>):integer|K62
_slice_length(<group-idx>, <slice-idx>):integer|K62
_slice_loop_count(<group-idx>, <loop-idx>):integer|K62
_slice_start(<group-idx>, <slice-idx>):integer|K62
_will_never_terminate(<event-id>)|K55
abs(<real-value>):real|K56
acos(<real-value>):real|K56
add_menu_item(<variable>, <text>, <number>)|K62
add_text_line(<variable>, <text>)|K62
allow_group(<group-idx>)|K62
array_equal(<array-variable>, <array-variable>):boolean|K62
asin(<real-value>):real|K56
atan(<real-value>):real|K56
attach_level_meter(<ui-id>, <group-idx>, <slot-idx>, <channel-idx>, <bus-idx>)|K62
attach_zone(<waveform>, <zone-id>, <parameter>)|K62
by_marks(<bit-mark>):integer|K55
by_track(<track-idx>):integer|K62
cc_delivery_request(<controller-number>)|K55
ceil(<real-value>):real|K56
change_listener_par(<signal-type>, <parameter>)|K62
change_note(<event-id>, <new-note-number>)|K62
change_pan(<event-id>, <panorama>, <relative-bit>)|K62
change_time_with_pitch(<event-id>, <time>):integer|K62
change_tune(<event-id>, <tune-amount>, <relative-bit>)|K62
change_velo(<event-id>, <new-velocity-number>)|K62
change_vol(<event-id>, <volume>, <relative-bit>)|K62
cbrt(<real-value>):real|K71
cos(<real-value>):real|K56
dec(<expression>):integer|K55
delay_event_for_loading_slots(<unknown>)|K62
delete_event_mark(<event-id>, <bit-mark>)|K62
detect_pitch(<zone-id>, <return-variable>):integer|K62
detect_rms(<zone-id>, <return-variable>):integer|K62
detect_peak(<zone-id>, <return-variable>):integer|K62
detect_loudness(<zone-id>, <return-variable>):integer|K62
detect_sample_type(<zone-id>, <return-variable>):integer|K62
detect_instrument_type(<zone-id>, <return-variable>):integer|K62
detect_drum_type(<zone-id>, <return-variable>):integer|K62
disable_logging(<log-type>)|K62
disallow_group(<group-idx>)|K62
dont_use_machine_mode(<event-id>)|K62
event_status(<event-id>):integer|K62
exit()|K55
exp(<real-value>):real|K56
exp2(<real-value>):real|K71
fade_in(<event-id>, <fade-time>)|K62
fade_out(<event-id>, <fade-time>, <stop-voice>)|K62
find_group(<group-name>):integer|K55
find_mod(<group-idx>, <mod-name>):integer|K62
find_target(<group-idx>, <mod-idx>, <target-name>):integer|K62
find_zone(<sample-name>):integer|K55
floor(<real-value>):real|K56
fs_get_filename(<ui-id>, <return-parameter>):string|K62
fs_navigate(<ui-id>, <direction>)|K62
get_control_par(<ui-id>, <control-parameter>):integer|K62
get_control_par_arr(<ui-id>, <control-parameter>, <index>):integer|K62
get_control_par_real_arr(<ui-id>, <control-parameter>, <index>):real|K71
get_control_par_str(<ui-id>, <control-parameter>):string|K62
get_control_par_str_arr(<ui-id>, <control-parameter>, <index>):string|K62
get_engine_par(<parameter>, <group>, <slot>, <generic>):integer|K62
get_engine_par_disp(<parameter>, <group>, <slot>, <generic>):string|K62
get_engine_par_disp_m(<parameter>, <instrument-slot-idx>, <slot>, <generic>):string|K62
get_engine_par_m(<parameter>, <instrument-slot-idx>, <slot>, <generic>):integer|K62
get_event_ids(<array-variable>)|K55
get_event_mark(<event-id>, <bit-mark>):integer|K66
get_event_par(<event-id>, <parameter>):integer|K62
get_event_par_arr(<event-id>, <parameter>, <group-idx>):integer|K62
get_folder(<path variable>):string|K55
get_font_id(<path-text>):integer|K60
get_group_idx(<group-name>):integer|K71
get_group_par(<group-idx>, <parameter>):integer|K63
get_key_color(<note-number>):integer|K55
get_key_name(<note-number>):integer|K55
get_key_triggerstate(<note-number>):integer|K55
get_key_type(<note-number>):integer|K55
get_keyrange_max_note(<note-number>):integer|K55
get_keyrange_min_note(<note-number>):integer|K55
get_keyrange_name(<note-number>):integer|K55
get_loop_par(<zone-id>, <loop-id>, <parameter>):integer|K62
get_menu_item_str(<ui-id>, <index>):string|K62
get_menu_item_value(<ui-id>, <index>):integer|K62
get_menu_item_visibility(<ui-id>, <index>):integer|K62
get_mod_idx(<group-idx>, <mod-name>):integer|K71
get_num_zones():integer|K71
get_purge_state(<group-idx>):integer|K62
get_sample(<zone-id>,<return-parameter>):string|K62
get_sample_length(<zone-id>):integer|K55
get_target_idx(<group-idx>, <mod-idx>, <target-name>):integer|K71
get_ui_id(<variable>):integer|K55
get_ui_wf_property(<waveform>, <property>, <index>):integer|K62
get_voice_limit(<voice­type>):integer|K60
get_zone_id(<zone-idx>):integer|K71
get_zone_par(<zone-id>, <parameter>):integer|K62
get_zone_status(<zone-id>):integer|K71
group_name(<group-idx>):string|K62
guiidx_to_slotidx(<instrument-gui-idx>):integer|K62
hide_part(<variable>, <value>)|K62
ignore_controller()|K55
ignore_event(<event-id>)|K62
ignore_midi()|K55
import_nckp(<path variable>):string|K63
in_range(<expression>, <lower>, <upper>):boolean|K62
inc(<expression>)|K55
int(<real-value>):integer|K71
int_to_real(<integer>):real|K56
is_zone_empty(<zone-id>):integer|K63
iterate_macro(<expression>)|K57
literate_macro(<expression>)|K57
load_array(<array-or-string-array-variable>, <mode>):integer|K62
load_array_str(<array-or-string-array-variable>, <path-text>):integer|K62
load_ir_sample(<file-name>, <slot>, <generic>):integer|K62
load_ir_sample_m(<file-name>, <output-number>, <slot>, <generic>):integer|K62
load_native_ui(<path-text>)|K70
load_midi_file(<path-text>):integer|K57
load_patch(<path-text>, <instrument-slot-idx>)|K62
load_performance_view(<file-name>):string|K62
log(<real-value>):real|K56
log2(<real-value>):real|K71
log10(<real-value>):real|K71
lsb(<variable>):integer|K55
make_instr_persistent(<variable>)|K55
make_perfview()|K55
make_persistent(<variable>)|K55
message(<variable-or-text>)|K62
mf_copy_export_area(<zone-id>)|K64
mf_get_buffer_size():integer|K55
mf_get_byte_one():integer|K55
mf_get_byte_two():integer|K55
mf_get_channel():integer|K55
mf_get_command():integer|K55
mf_get_event_par(<event-id>, <parameter>):integer|K62
mf_get_first(<track-idx>)|K62
mf_get_id():integer|K55
mf_get_last(<track-idx>)|K62
mf_get_length():integer|K55
mf_get_mark(<event-id>, <mark>):integer|K62
mf_get_next(<track-idx>)|K62
mf_get_next_at(<track-idx>, <pos>)|K62
mf_get_note_length():integer|K56
mf_get_num_tracks():integer|K55
mf_get_pos():integer|K55
mf_get_prev(<track-idx>)|K62
mf_get_prev_at(<track-idx>, <pos>)|K62
mf_get_track_idx():integer|K55
mf_insert_event(<track>, <pos>, <command>, <byte1>, <byte2>):integer|K62
mf_insert_file(<path-text>, <track-offset>, <position-offset>, <mode>):integer|K62
mf_remove_event(<event-id>)|K55
mf_reset():integer|K57
mf_set_buffer_size(<size>):integer|K57
mf_set_byte_one(<par>)|K55
mf_set_byte_two(<par>)|K55
mf_set_channel(<midi-channel>)|K55
mf_set_command(<par>)|K55
mf_set_event_par(<event-id>, <parameter>, <value>)|K62
mf_set_export_area(<name>, <start-pos>, <end-pos>, <start-track>, <end-track>):integer|K62
mf_set_note_length(<value>)|K57
mf_set_num_export_areas(<value>)|K64
mf_set_length(<par>)|K55
mf_set_mark(<event-id>, <mark>, <status>)|K62
mf_set_pos(<par>)|K55
move_control(<variable>, <xpos>, <ypos>)|K62
move_control_px(<variable>, <x-position>, <y-position>)|K62
ms_to_ticks(<microseconds>):integer|K55
msb(<variable>):integer|K55
note_off(<event-id>)|K62
num_elements(<any-array-variable>):integer|K55
num_slices(<group-idx>):integer|K62
num_slices_zone(<zone-id>):integer|K55
output_channel_name(<output-number>):integer|K55
pgs_create_key(<key-id>, <size>)|K62
pgs_create_str_key(<key-id>)|K55
pgs_get_key_val(<key-id>, <index>):integer|K62
pgs_get_str_key_val(<key-id>):string|K55
pgs_key_exists(<key-id>):boolean|K55
pgs_set_key_val(<key-id>, <index>, <value>)|K62
pgs_set_str_key_val(<key-id>, <text>)|K62
pgs_str_key_exists(<key-id>):boolean|K55
play_note(<note-number>, <velocity>, <sample-offset>, <duration>):integer|K62
pow(<real-value>, <real-value>):real|K62
purge_group(<group-idx>, <mode>):integer|K62
random(<min>, <max>):integer|K62
read_persistent_var(<variable>)|K55
real(<integer>):real|K71
real_to_int(<real-value>):integer|K56
redirect_midi(<unknown>)|K55
redirect_output(<event-id>, <type>, <output-number>)|K55
remove_keyrange(<key-number>)|K55
reset_engine()|K55
reset_ksp_timer()|K55
reset_rls_trig_counter(<note>)|K55
round(<real-value>):real|K56
save_array(<array-or-string-array-variable>, <mode>):integer|K62
save_array_str(<array-or-string-array-variable>, <path-text>):integer|K62
save_midi_file(<path-text>):integer|K57
search(<array-variable>, <value>):integer|K62
set_bounds(<control>, <x>, <y>, <width>, <height>)|K55
set_button_properties(<button>, <text>, <picture>, <text-alignment>, <font-type>, <textpos-y>)|K55
set_control_help(<variable>, <text>)|K62
set_control_par(<ui-id>, <control-parameter>, <value>)|K62
set_control_par_arr(<ui-id>, <control-parameter>, <value>, <index>)|K62
set_control_par_real_arr(<ui-id>, <control-parameter>, <real-value>, <index>)|K71
set_control_par_str(<ui-id>, <control-parameter>, <text>)|K62
set_control_par_str_arr(<ui-id>, <control-parameter>, <text>, <index>)|K62
set_controller(<controller-number>, <controller-value>)|K62
set_engine_par(<parameter>, <value>, <group>, <slot>, <generic>):integer|K62
set_engine_par_m(<parameter>, <value>, <instrument-slot-idx>, <slot>, <generic>):integer|K62
set_event_mark(<event-id>, <bit-mark>)|K62
set_event_par(<event-id>, <parameter>, <value>)|K62
set_event_par_arr(<event-id>, <parameter>, <value>, <group-idx>)|K62
set_group_dyn_par_name(<group-dyn-par>, <name>)|K62
set_key_color(<note-number>, <key-color-constant>)|K62
set_key_name(<key-number>, <key-name>)|K62
set_key_pressed(<key-number>, <value>)|K62
set_key_pressed_support(<value>)|K55
set_key_type(<note-number>, key-type-constant>)|K62
set_keyrange(<key-number1>, <key-number2>, <range-name>)|K62
set_knob_defval(<knob-variable>, <value>)|K62
set_knob_label(<knob-variable>, <text>)|K62
set_knob_properties(<knob>, <text>, <default>)|K55
set_knob_unit(<knob-variable>, <unit>)|K62
set_label_properties(<label>, <text>, <picture>, <text-alignment>, <font-type>, <textpos-y>)|K55
set_level_meter_properties(<level-meter>, <bg-color>, <off-color>, <on-color>, <overload-color>)|K55
set_listener(<signal-type>, <parameter>)|K62
set_loop_par(<zone-id>, <loop-id>, <parameter>, <value>):integer|K62
set_menu_item_str(<menu-id>, <index>, <text>)|K62
set_menu_item_value(<menu-id>, <index>, <value>)|K62
set_menu_item_visibility(<menu-id>, <index>, <visibility>)|K62
set_menu_properties(<menu>, <picture>, <font-type>, <text-alignment>, <textpos-y>)|K55
set_midi(<channel>, <command>, <byte1>, <byte2>)|K62
set_nrpn(<address>, <value>)|K62
set_num_user_zones(<size>)|K62
set_rpn(<address>, <value>)|K62
set_sample(<zone-id>, <path-text>):integer|K62
set_script_title(<text>)|K55
set_skin_offset(<offset>)|K55
set_slider_properties(<slider>, <default>, <picture>, <mouse-behaviour>)|K55
set_snapshot_type(<type>)|K55
set_switch_properties(<switch>, <text>, <picture>, <text-alignment>, <font-type>, <textpos-y>)|K55
set_table_properties(<table>, <bar-color>, <zero-line-color>)|K55
set_table_steps_shown(<array-variable>, <num-steps>)|K62
set_text(<variable>, <text>)|K62
set_text_edit_properties(<text-edit>, <text>, <picture>, <text-alignment>, <font-type>, <textpos-y>)|K55
set_ui_color(<hex-value>)|K56
set_ui_height(<height>)|K55
set_ui_height_px(<height>)|K55
set_ui_wf_property(<waveform>, <property>, <index>, <value>)|K62
set_ui_width_px(<width>)|K56
set_value_edit_properties(<value-edit>, <text>, <font-type>, <textpos-y>, <show-arrows>)|K55
set_voice_limit(<voice­type>,<value>)|K55
set_waveform_properties(<waveform>, <bar-color>, <zero-line-color>, <bg-color>, <bg-alpha>, <wave-color>, <wave-cursor-color>, <slicemarkers-color>, <wf-vis-mode>)|K55
set_wavetable2d_properties(<wavetable>, <wt-zone>, <bg-color>, <bg-alpha>, <wave-color>, <wave-alpha>, <wave-end-color>, <wave-end-alpha>)|K60
set_wavetable3d_properties(<wavetable>, <wt-zone>, <bg-color>, <bg-alpha>, <wavetable-color>, <wavetable-alpha>, <wavetable-end-color>, <wavetable-end-alpha>, <parallax-x>, <parallax-y>)|K60
set_zone_par(<zone-id>, <parameter>, <value>):integer|K62
sgn(<real-value>):integer|K71
sh_left(<expression>, <amount>):integer|K62
sh_right(<expression>, <amount>):integer|K62
show_library_tab()|K55
signbit(<real-value>):integer|K71
sin(<real-value>):real|K56
slice_idx_loop_end(<group-idx>, <loop-idx>):integer|K62
slice_idx_loop_start(<group-idx>, <loop-idx>):integer|K62
slice_length(<group-idx>, <slice-idx>):integer|K62
slice_loop_count(<group-idx>, <loop-idx>):integer|K62
slice_start(<group-idx>, <slice-idx>):integer|K62
slotidx_to_guiidx(<instrument-slot-idx>):integer|K62
sort(<array-variable>, <direction>)|K62
sqrt(<real-value>):real|K56
stop_wait(<callback-id>, <par>)|K62
tan(<real-value>):real|K56
ticks_to_ms(<ticks>):integer|K55
unload_slot(<instrument-slot-idx>)|K62
wait(<wait-time>)|K55
wait_async(<event-id>):integer|K62
watch_var(<variable>)|K60
watch_array_idx(<any-array-variable>, <index>)|K62
wait_ticks(<wait-time>)|K55
will_never_terminate(<event-id>)|K55
zone_slice_idx_loop_end(<zone-id>, <loop-idx>):integer|K62
zone_slice_idx_loop_start(<zone-id>, <loop-idx>):integer|K62
zone_slice_length(<zone-id>, <slice-idx>):integer|K62
zone_slice_loop_count(<zone-id>, <loop-idx>):integer|K62
zone_slice_start(<zone-id>, <slice-idx>):integer|K62

[functions_with_forced_parentheses]
mf_reset|K55
mf_get_buffer_size|K55
mf_get_byte_one|K55
mf_get_byte_two|K55
mf_get_channel|K55
mf_get_command|K55
mf_get_buffer_size|K56
mf_get_byte_one|K56
mf_get_byte_two|K56
mf_get_channel|K56
mf_get_command|K56

[functions_with_constant_return]
abs|K55
acos|K56
asin|K56
atan|K56
by_marks|K55
by_track|K55
cos|K56
exp|K56
floor|K56
get_ui_id|K55
log|K56
lsb|K56
num_elements|K55
pow|K56
sin|K56
sqrt|K56
tan|K56

[keywords]
_pgs_changed|K55
and|K55
as|K57
call|K55
case|K55
const|K55
controller|K55
declare|K55
downto|K55
else|K55
end|K55
end family|K55
end for|K55
end function|K55
end if|K55
end macro|K55
end on|K55
end_on|K55
end property|K55
end select|K55
end taskfunc|K55
end while|K55
family|K55
for|K55
function|K55
if|K55
import|K55
init|K55
macro|K55
midi_in|K55
not|K55
note|K55
nrpn|K55
on|K55
on async_complete|K55
on controller|K55
on init|K55
on listener|K55
on midi_in|K55
on note|K55
on nrpn|K55
on persistence_changed|K55
on pgs_changed|K55
on_pgs_changed|K55
on poly_at|K55
on release|K55
on rpn|K55
on ui_control|K55
on ui_update|K55
or|K55
out|K55
override|K55
pgs_changed|K55
poly_at|K55
property|K55
release|K55
rpn|K55
select|K55
step|K55
taskfunc|K55
to|K55
ui_control|K55
ui_update|K55
var|K55
while|K55

[string_typed_control_parameters]
$CONTROL_PAR_AUTOMATION_NAME|K55
$CONTROL_PAR_BASEPATH|K55
$CONTROL_PAR_CURSOR_PICTURE|K57
$CONTROL_PAR_FILEPATH|K55
$CONTROL_PAR_HELP|K55
$CONTROL_PAR_LABEL|K55
$CONTROL_PAR_PICTURE|K55
$CONTROL_PAR_TEXT|K55
$CONTROL_PAR_TEXTLINE|K55
'''